#!/bin/ash

# Add script function
source /root/.script_base/base

# add packages
PACK_DEFAULT="  apache-mod-fcgid php5 php5-dev php5-apache2 php5-fpm php5-gd php5-mysql php5-pear\
                php5-mysqli php5-common php5-curl php5-pear php5-iconv php5-imap \

                php5-mcrypt php5-pspell php5-phar php5-sqlite3 php5-xml php5-xmlrpc php5-xmlreader \
                php5-xsl php5-gettext php5-xsl php5-opcache php5-json php5-bz2 php5-sockets php5-zip php5-bcmath \
                php5-pdo_sqlite php5-posix php5-gmp php5-openssl php5-ctype php5-calendar \

                ttf-freefont fontconfig libxrender imagemagick
            "

#php5-intl & cli

# install pakage
install_pack

# Configuration Apache part 2 
sed -i "s/variables_order.*/variables_order = \"EGPCS\"/g" /etc/php5/php.ini && \
sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/httpd.conf

# add phpunit
apk add --update ca-certificates openssl && update-ca-certificates

wget https://phar.phpunit.de/phpunit-5.7.phar && \
    chmod +x phpunit-5.7.phar && \
    mv phpunit-5.7.phar /usr/local/bin/phpunit && \
    phpunit --version

# update and upgrade
update_sys

# clean system
clean