#!/bin/ash

# Add script function
source /root/.script_base/base

# add packages
PACK_DEFAULT="  dpkg-dev dpkg apache-mod-fcgid php5-apache2 php5 php5-fpm \
                php5-gd php5-mysql php5-mysqli php5-cli php5-common php5-curl php5-intl php5-pear \

                php5-imagick php5-imap php5-mcrypt php5-memcache  php5-pspell php5-phar\
                php5-sqlite3  php5-xmlrpc php5-xsl  php5-gettext \
                php5-opcache php5-json php5-apcu php5-bz2 php5-sockets php5-zip ssmtp php5-bcmath \

                 php5-gmp libxrender php5-xdebug php5-soap ssmtp dpkg xvfb dbus ttf-freefont fontconfig
                 "

# install pakage
install_pack

# Configuration Apache part 2 
sed -i "s/variables_order.*/variables_order = \"EGPCS\"/g" /etc/php5/php.ini && \
sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/httpd.conf


# add phpunit
apk add --update ca-certificates openssl && update-ca-certificates

wget https://phar.phpunit.de/phpunit-5.7.phar && \
    chmod +x phpunit-5.7.phar && \
    mv phpunit-5.7.phar /usr/local/bin/phpunit && \
    phpunit --version

# update and upgrade
update_sys

# clean system
clean